# Generated by Django 3.0.6 on 2020-05-29 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200528_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='timetable',
            new_name='timeTable',
        ),
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='timeTables', to='API.Business'),
        ),
    ]
