# Generated by Django 3.0.6 on 2020-06-06 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200529_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200, null=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pictures', to='API.Business')),
            ],
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200, null=True)),
                ('messageId', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='cancellation_range',
            field=models.IntegerField( default=None,null=True),
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='servicefile',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pictures', to='API.Service'),
        ),
    ]
