# Generated by Django 3.0.6 on 2020-06-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20200606_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sans',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='sans',
            name='startTime',
        ),
        migrations.AddField(
            model_name='sans',
            name='endTimeHour',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sans',
            name='endTimeMinute',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sans',
            name='startTimeHour',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sans',
            name='startTimeMinute',
            field=models.SmallIntegerField(default=0),
        ),
    ]
