<<<<<<< HEAD
# Generated by Django 3.0.6 on 2020-06-15 17:30
=======
# Generated by Django 3.0.6 on 2020-06-15 21:38
>>>>>>> d98e0692db5a6ccc9a44e76299e5ce231575729e

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20200606_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 17, 30, 50, 856896)),
        ),
    ]
