# Generated by Django 3.0.6 on 2020-07-05 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_reserve_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sans',
            name='endTimeHour',
        ),
        migrations.RemoveField(
            model_name='sans',
            name='endTimeMinute',
        ),
        migrations.RemoveField(
            model_name='sans',
            name='startTimeHour',
        ),
        migrations.RemoveField(
            model_name='sans',
            name='startTimeMinute',
        ),
        migrations.AddField(
            model_name='sans',
            name='endTime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='sans',
            name='startTime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 13, 51, 38, 717369)),
        ),
    ]
