# Generated by Django 3.0.6 on 2020-07-05 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20200705_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='date',
        ),
        migrations.AlterField(
            model_name='reserve',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 14, 41, 55, 89336)),
        ),
    ]
