# Generated by Django 3.0.6 on 2020-07-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_auto_20200706_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
