# Generated by Django 3.0.6 on 2020-07-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_auto_20200705_2205'),
        ('API', '0013_auto_20200706_1211'),
    ]

    operations = [
    ]
