# Generated by Django 3.0.6 on 2020-07-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_merge_20200706_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
