# Generated by Django 3.0.6 on 2020-07-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_auto_20200707_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagefile',
            old_name='messageId',
            new_name='ticketId',
        ),
    ]
