# Generated by Django 3.0.6 on 2020-07-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_transaction_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='API.Wallet'),
            preserve_default=False,
        ),
    ]
