# Generated by Django 3.0.6 on 2020-07-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_auto_20200710_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('request', models.TextField(null=True)),
                ('response', models.TextField(null=True)),
                ('createdAt', models.DateTimeField(null=True)),
            ],
        ),
    ]
